### ISSUE TITLE
ModuleNotFoundError: No module named 'views'

### ISSUE THREAD

**Issue by francesco1119** [balusarakesh/yelp#2]
If I run `python .\manage.py runserver` I receive:

```
from views import index
ModuleNotFoundError: No module named 'views'
```

(this happens with PowerShell, Linux Shell works fine)

**Comment by ChandrasekarPerumal** [comment]
Mention your app name it will work fine

from <appName>.views import index

**Comment by francesco1119** [comment]
HI @ChandrasekarPerumal , 
4 years is a lot for a reply. Because you reply was too late I had to use GoogleMaps API for my project: 

https://github.com/francesco1119/Fantail

It's OK, if I have time I will do that for Yelp too. 

Thank you

**Comment by ChandrasekarPerumal** [comment]
Hahaha.. I just encounter the issue today, got the answer and that I shared to you.. 😊
